unzip("activity.zip")
activity<-read.csv("activity.csv")
tots<-aggregate(steps~date,data=activity,sum)
hist(tots$steps)
#aves<-aggregate(steps~date,data=activity,mean)
#print(aves)
meanSteps<-mean(tots$steps)
medianSteps<-median(tots$steps)
print(paste("Mean total steps per day: ",meanSteps))
print(paste("Median total steps per day: ",medianSteps))
unlink("activity.csv")